### ISSUE TITLE
npm start 出现错误

### ISSUE THREAD

**Issue by oscnet** [eoscannon/EosCannon-Offline-Tools#1]
不知道是哪里出现问题
```bash
OSCiMac:EosCannon-Offline-Tools oscar$ npm start

> react-boilerplate@3.6.0 start /Users/oscar/dev/EosCannon-Offline-Tools
> cross-env NODE_ENV=development node server

module.js:545
    throw err;
    ^

Error: Cannot find module '/Users/oscar/dev/EosCannon-Offline-Tools/server'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-boilerplate@3.6.0 start: `cross-env NODE_ENV=development node server`
```

**Comment by echocamel** [comment]
+1

**Comment by zhujingxing** [comment]
Did you pre install node? I'm sorry, I didn't explain it in Readme。

**Comment by zhuxx2021** [comment]
This may be due to the installation error of antd, 
because you need to introduce moment yourself before antd@3.0 introduces antd.js. 
So, moment is added to package.json. Now it can start normally.
